//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logo_Manager2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:antoinecouck.database.windows.net,1433;Initial Catalog=Logo_manager2;P" +
            "ersist Security Info=False;User ID=antoinecouck;Password=Dotnetexamen9;MultipleA" +
            "ctiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeo" +
            "ut=30;")]
        public string Logo_manager2ConnectionString {
            get {
                return ((string)(this["Logo_manager2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=antoinecouck.database.windows.net;Initial Catalog=Logo_manager2;User " +
            "ID=antoinecouck;Password=Dotnetexamen9")]
        public string Logo_manager2ConnectionString1 {
            get {
                return ((string)(this["Logo_manager2ConnectionString1"]));
            }
        }
    }
}
